/** Wording you might want to tweak without hunting through screens. */
export const copy = {
  pickTeam: 'Pick the team this app should follow.',
  pickTeamHint: 'You can change it later. Everyone else is still one tap away.',
  confirmTeam: 'This is my team',
  updateTeam: 'Update my team',
  yourTeam: 'Yours',
  picked: 'Picked',
  setAsTeam: 'Follow this team',
  alreadyYours: 'This is your team',
  live: 'Live',
  final: 'Final',
  upcoming: 'Upcoming',
  alsoOn: 'Also on',
  upNext: 'Up next',
  thisWeek: 'This week',
  kickoff: 'Kickoff',
  fromBuilding: 'From the building',
  fromBuildingHint: 'A coach line or one team note, when there is one. Not every article.',
  teamColors: 'Team colors',
  teamColorsHint: 'The whole app takes on your club: field color, cards, and the mark in the header. Turn it off for the plain gold look.',
  on: 'On',
  off: 'Off',
  tapToSwap: 'Tap a game to put it up front.',
  yourClub: 'Your team',
  openTeam: 'Full sheet',
  moreNumbers: 'More numbers',
  fewerNumbers: 'Fewer numbers',
  lastGameLeaders: 'Last game leaders',
  leadersHint: 'These are from the last game we have, not a season-long leaderboard.',
  seasonPace: 'Season pace, not this game.',
  injuries: 'Injuries',
  injuriesHint: 'Statuses move all week. This is the latest report, not a doctor.',
  division: 'Division',
  divisionHint: 'Good to know: the race around your club.',
  aroundLeague: 'Around the league',
  nflRules: 'NFL rules',
  nflRulesHint: 'Most looked-up first',
  nflRulesIntro:
    'Short reminders, from the flags and questions that come up most to the ones that rarely do. Not the league’s official book. The referee still has the call.',
  nflRulesEmpty: 'No rule matched that.',
  noNews: 'No headlines right now.',
  noLive: 'Nothing is live. Here is your club.',
  checking: 'Checking the slate…',
  stale: 'Showing the last save. The feed did not answer.',
  failed: 'The feed did not answer, and there is nothing saved on this phone yet.',
  pull: 'Pull to try again.',
  updated: 'Updated',
  settings: 'Settings',
  changeTeam: 'Change team',
  clearCache: 'Clear saved stats',
  cacheCleared: 'Saved stats cleared. Your team stayed.',
  creditsTitle: 'Where the numbers come from',
  credits:
    'Scores, news, rosters, and stat lines are read from ESPN’s public site data. FootballTLDR is not affiliated with the NFL or ESPN. Lines and odds are never shown. If a number is missing, the row is hidden instead of filled with a zero.',
  editHint:
    'Name, tagline, logo flag, colors, and which stats are “main” live in src/config. The plan is docs/memories/plan.md.',
  fantasyTitle: 'Fantasy, on this phone',
  fantasyIntro:
    'A builder for your own sheet. It does not join a league, draft against anyone, or talk to another phone.',
  rules: 'Rules',
  customSheet: 'Custom rule sheet',
  punishments: 'Punishment log',
  roster: 'Roster builder',
  rosterDek: 'Fill the lineup on your rule sheet. Active players only.',
  addToSheet: 'Add to the sheet',
  notActive: 'Not on an active roster. You can look them up, but they cannot be added.',
  openSlot: 'Open',
  addDefense: 'Add a defense',
  watch: 'Watch',
  watchIntro: 'Keep an eye on other teams, and on players who are not on the club you follow.',
  watchPlayer: 'Watch',
  watching: 'Watching',
  unwatch: 'Stop watching',
  watchTeam: 'Watch this team',
  unwatchTeam: 'Stop watching this team',
  watchedTeams: 'Teams',
  watchedPlayers: 'Players',
  addWatchTeam: 'Add a team',
  noWatchTeams: 'No extra teams yet.',
  noWatchPlayers: 'No players yet. Search a name and open the page.',
  inactiveNote: 'Not on an active roster. The stat line is still here.',
  playerClubs: 'Clubs',
  playerLatest: 'Latest',
  playerNews: 'News',
  playerInjury: 'Injury report',
  playerExperience: 'Experience',
  playerCollege: 'College',
  playerDraft: 'Draft',
  playerJersey: 'Jersey',
  playerTitle: 'Player',
  exportSheet: 'Export sheet',
  exportHint: 'House rules and the punishment log leave with the phone unless you send them out.',
  exportWeb: 'Copy this. The browser preview cannot hand the file to another app.',
  rulesIntro:
    'Plain-language versions of the three common scoring styles. They are not an official league document. Your custom sheet is the one this phone uses for the rough point totals.',
  currentSheet: 'Sheet in use',
  savedHere: 'Saved on this phone.',
  sheetName: 'Sheet name',
  scoring: 'Scoring',
  rosterSlots: 'Roster slots',
  houseNotes: 'House notes',
  applyPreset: 'Start from a preset',
  who: 'Who',
  owes: 'What they owe',
  week: 'Week',
  addPunishment: 'Add to the log',
  markDone: 'Done',
  markOpen: 'Not yet',
  emptyPunishments: 'Nothing owed yet. Add one when the league decides a forfeit.',
  remove: 'Remove',
  findPlayer: 'Find',
  searchHint: 'Search a name. A close spelling still counts. Only active players can be added, and only into an open spot.',
  noPlayers: 'No NFL players matched.',
  adding: 'Pulling the stat line…',
  statMiss: 'Stat line did not load. The player is still on your sheet.',
  emptyRoster: 'No one on the sheet yet.',
  pointsLabel: 'Rough total',
  pointsHint: 'Only stats we actually received are counted. This is not an official score.',
  glance: 'Start / sit glance',
  glancePick: 'Choose two at the same position.',
  glanceDisclaimer: 'A glance, not advice.',
  needTwo: 'Add two players at the same position to compare them.',
  back: 'Back',
  settingsShort: 'Set',
  skip: 'Tap to enter',
  loadingField: 'Painting the field',
  noneScheduled: 'No upcoming game on the schedule we have.',
  scores: 'Scores',
  schedule: 'Schedule',
  bye: 'Bye',
  noScores: 'No finished games on the schedule yet.',
  playoffPicture: 'Playoff picture',
  playoffNote:
    'If the season ended today. Seed 1 sits the first weekend. The wild-card games are 2 against 7, 3 against 6, and 4 against 5, with the higher seed at home. After that weekend the league reseeds, so a path to the Super Bowl is not set yet. The Super Bowl is the AFC winner against the NFC winner.',
  playoffLiveNote: 'These are the playoff games on the schedule. Later rounds are reseeded until they are played. The Super Bowl is the AFC winner against the NFC winner.',
  playoffIfEnded: 'Wild card, if it ended today',
  playoffBye: 'Bye',
  playoffDivision: 'Division',
  playoffWild: 'Wild card',
  playoffOut: 'Outside',
  noInjuries: 'No one listed out, doubtful, or questionable.',
  moreInjuries: 'more',
  gearLabel: 'Settings',
  home: 'Home',
  league: 'League',
  fantasy: 'Fantasy',
  searchTeams: 'Search teams',
  searchLeague: 'Teams or players',
  pinnedPlayers: 'Pinned',
  players: 'Players',
  noRoster: 'No one listed on this roster.',
  pin: 'Pin',
  unpin: 'Unpin',
  playbook: 'Playbook',
  playbookIntro:
    'Tap a play for a published diagram, then the write-up. The pictures are real diagrams from Wikimedia Commons, matched to that play. Man coverage and a quarterback sneak stay as words, because the name is the picture. If a row says there is no diagram, I did not have a picture I could trust for that exact play. Not a secret team sheet.',
  playbookNoArt: 'No published diagram for this one. The notes are the guide.',
  playbookArtMiss: 'That picture did not load. The notes are still the guide.',
  playbookEmpty: 'No play matched that.',
  playbookAll: 'All',
  clear: 'Clear',
}
