/**
 * Broadcast-level football, grouped so you can skim and then open a play.
 * Not one club's secret sheet. Edit the order here if you want a family higher.
 */
export type PlayEntry = {
  id: string
  name: string
  look: string
  how: string
  tell: string
  call: string
  answer: string
}

export type PlaySection = {
  id: string
  title: string
  dek: string
  plays: PlayEntry[]
}

export const playbook: PlaySection[] = [
  {
    id: 'formations',
    title: 'Formations',
    dek: 'Read this before the snap. The personnel and the shape tell you what family of play is coming.',
    plays: [
      {
        id: '11',
        name: '11 personnel',
        look: 'One back, one tight end, three receivers.',
        how: 'This is the usual NFL snap. The tight end can block, chip a rusher, or release as a fourth receiver. The back can run, protect, or leak out.',
        tell: 'Count the eligible bodies. Three split wide, one tight to the line, one next to the quarterback.',
        call: 'The base for zone, play action, and the whole quick game. If you only learn one package, learn this one.',
        answer: 'Nickel is the usual answer: a slot corner replaces a linebacker. If they stay in a big front against 11, throw. If they stay small against a heavier set, run.',
      },
      {
        id: '12',
        name: '12 personnel',
        look: 'One back, two tight ends, two receivers.',
        how: 'Heavier than 11. The extra tight end kicks out on power, climbs on zone, or slips out late as a surprise receiver.',
        tell: 'Two players tight to the line, only two split wide.',
        call: 'Run, or play action off the run you just showed. A second tight end is a tell that they want to move people, not just throw quick.',
        answer: 'A light nickel gets pushed around. A base front can fit the run. If you bring the big front and they throw play action, the post behind a biting safety is the shot.',
      },
      {
        id: '21',
        name: '21 personnel',
        look: 'Two backs, one tight end, two receivers.',
        how: 'Fullback football. The second back leads on power, counter, and iso. He is a blocker first.',
        tell: 'Two players in the backfield and a tight end. Often under center.',
        call: 'Power, counter, lead. The fullback is the point of the run.',
        answer: 'Fit the lead blocker with a linebacker who takes him on, not one who runs around him. After a few of these, watch for the play-action cross, because the linebackers are triggering downhill.',
      },
      {
        id: 'empty',
        name: '10 personnel and empty',
        look: 'Four or five receivers. Empty means nobody next to the quarterback.',
        how: 'Pass first. A run from empty is a quarterback draw or a sneak, not a handoff. Empty also makes the protection thin, so the ball has to come out.',
        tell: 'No tight end, or five split out with an empty backfield.',
        call: 'When you want the defense in nickel or dime and you like a matchup. Quick game and shots, not a 7-step drop.',
        answer: 'Dime or a zero blitz. If you see no safety and a crowded line against empty, the ball is coming hot. Do not take a deep drop.',
      },
      {
        id: 'gun',
        name: 'Shotgun, pistol, under center',
        look: 'Where the quarterback puts his hands.',
        how: 'Under center, his hands are down and the run looks real, which makes play action better. Shotgun, he is back and the pass is the lean. Pistol puts the back directly behind him so the run still looks like under center.',
        tell: 'Hands under the center, or the quarterback standing five yards back. Pistol is shotgun depth with the back lined up behind him, not beside him.',
        call: 'Under center to sell the run. Shotgun to throw. Pistol when you want both.',
        answer: 'Do not treat every shotgun snap as a pass. Zone and draw from the gun are normal. Do not treat every under-center snap as a run. That is how play action works.',
      },
      {
        id: 'trips',
        name: 'Trips',
        look: 'Three receivers to one side.',
        how: 'The defense has to spin a safety or a nickel that way. Flood, spacing, and the seam all live here. The single receiver on the backside is often the alert if everyone spins over.',
        tell: 'Three to a side, one on the other.',
        call: 'When you want to overload one side of the coverage.',
        answer: 'Spin a defender over, but keep one honest on the single backside receiver. If the whole defense slides, throw the backside.',
      },
      {
        id: 'bunch',
        name: 'Bunch',
        look: 'Three receivers standing close together.',
        how: 'The point is a rub. Two of them cross or sit so a man-coverage defender has to run through a teammate. Zone just zones the area and the rub matters less.',
        tell: 'A cluster, not a spread. Often near the hash or the numbers.',
        call: 'Against man. Mesh and flat-slant from a bunch are the usual calls.',
        answer: 'Play zone, or switch the man assignments so your defenders do not chase through the pile. Chasing through a bunch is how you give up an easy catch.',
      },
      {
        id: 'motion',
        name: 'Motion',
        look: 'Somebody is running before the snap.',
        how: 'Jet motion across the formation is a sweep or a fake of one. Orbit motion is the wider version. Motion also tells the quarterback the coverage: if a defender follows, it is man. If nobody follows, it is zone.',
        tell: 'A receiver or a back jogging or sprinting along the line while the clock is still running.',
        call: 'To reveal man or zone, to set a sweep, or to move a blocker to the point of attack.',
        answer: 'Do not chase motion with the whole defense. One player accounts for the motion man. If you chase it, the run the other way is open.',
      },
    ],
  },
  {
    id: 'runs',
    title: 'Runs',
    dek: 'If the line moves together, it is zone. If a guard is pulling, it is gap: power, counter, or trap.',
    plays: [
      {
        id: 'inside-zone',
        name: 'Inside zone',
        look: 'The line steps the same way and the back cuts up the first hole.',
        how: 'Everyone steps playside together. A covered lineman blocks his man. An uncovered lineman helps, then climbs to a linebacker. The back presses the line and bends into daylight. He does not have a assigned hole.',
        tell: 'No pulling guard. The line moves as one. The back’s path is north-south with a late cut.',
        call: 'Against a passive or even front. It is the base run from 11 personnel and from the gun.',
        answer: 'Slant the tackles, or shoot a linebacker into the cutback lane. If they fit it hard, boot the other way or throw the glance behind the linebacker who stepped up. Split zone is the same run with a tight end kicking the backside end so that end cannot wreck it.',
      },
      {
        id: 'outside-zone',
        name: 'Outside zone',
        look: 'A wider stretch. The back can bounce, bend, or cut all the way back.',
        how: 'The line reaches playside, trying to get outside shoulder. The back aims at the tight end’s hip and reads the end: bounce if the end is blocked, bend if he is reached, cut back if the defense overruns it.',
        tell: 'Tackles reaching instead of driving straight back. The back is wider than on inside zone.',
        call: 'When you want the defense running sideways. It sets up the boot and the cutback.',
        answer: 'Set a hard edge and force the ball back inside, where a linebacker is waiting. If your end always crashes, they will keep it on a zone read or throw the boot behind him.',
      },
      {
        id: 'power',
        name: 'Power',
        look: 'A guard pulls and leads through the hole.',
        how: 'Down blocks on the frontside. The backside guard pulls and kicks or turns the linebacker in the hole. A fullback or H-back kicks the end. The back follows the puller. Dart is the same idea with the tackle pulling instead of the guard.',
        tell: 'A guard (or tackle) leaving his gap and running toward the play.',
        call: 'Short yardage, goal line, and whenever you want a hat on a hat at the point of attack.',
        answer: 'Wrong-arm the puller: hit him with the inside shoulder and spill the run outside, where help is. After they have leaned on power, counter the other way or boot away from the pulling guard.',
      },
      {
        id: 'counter',
        name: 'Counter',
        look: 'The back steps one way, then the ball goes the other way behind two pullers.',
        how: 'It is sold as outside zone or stretch. The guard and the tackle pull opposite the first step and lead the real run. The defense that chases the first step is out of the play.',
        tell: 'A false step, then two linemen pulling the other direction. Slower to the hole than power.',
        call: 'When the defense is fast to the stretch. You use their speed against them.',
        answer: 'Do not chase the first step. A scrape linebacker, or a backside defender who stays home, fits it. If they counter a lot, a slow screen to the fake side or a naked boot (the pullers are gone) is the surprise.',
      },
      {
        id: 'duo',
        name: 'Duo',
        look: 'Two double teams inside and a back who waits.',
        how: 'No puller. The line double-teams both defensive tackles and climbs to the linebackers. The back is patient, then runs at whichever linebacker the combo blocks.',
        tell: 'Two interior double teams, a vertical back, nobody pulling.',
        call: 'When linebackers are slow to trigger. It looks like inside zone until you notice nobody is reaching.',
        answer: 'A linebacker who fits downhill before the double team climbs. Play action off duo is the counter, because the line looks the same.',
      },
      {
        id: 'trap',
        name: 'Trap',
        look: 'A defender is left alone, then kicked from the side.',
        how: 'One defensive tackle is unblocked on purpose so he charges upfield. A guard pulls short and traps him. The hole is the gap he left. Wham is the trap blocked by a tight end coming across instead of a guard.',
        tell: 'One down lineman free for a beat, then hit sideways. A short pull, not a long one.',
        call: 'Against a tackle who always penetrates. You invite him up the field and block him after he has left his gap.',
        answer: 'That tackle squeezes and does not crash. A linebacker in the gap also fits it. If they trap you, they think your tackle is reckless. Play gap sound for a series and the trap has nobody to block.',
      },
      {
        id: 'toss',
        name: 'Toss and sweep',
        look: 'The back takes the ball outside with a lead blocker.',
        how: 'A pitch or a handoff to the perimeter. A fullback, tight end, or pulling guard leads. It is slower than jet motion and more of a convoy.',
        tell: 'The ball is clearly going wide, with a blocker in front of the back.',
        call: 'When the edge is soft or the defense is pinched inside.',
        answer: 'Set the edge and force it back inside. If you have been spilling everything inside, a pop pass or a throwback the other way is how they catch you.',
      },
      {
        id: 'draw',
        name: 'Draw',
        look: 'It starts as a pass. The back runs into the space the rushers left.',
        how: 'The line shows pass and lets the defensive line run upfield, then walls them off. The back waits a beat and runs through the empty middle.',
        tell: 'A pass set that does not sustain, and a back who does not release or pass-protect. Often on long yardage.',
        call: 'When the rush is up the field and the linebackers have dropped. Third and long is the classic down.',
        answer: 'A spy, or a tackle who does not rush past the ball. If they draw you, the next same look is often a shot, because you started sitting on the draw.',
      },
      {
        id: 'sneak',
        name: 'Quarterback sneak',
        look: 'The quarterback and the center drive forward for a yard.',
        how: 'No read. The center and the quarterback block the A gap and fall forward. Everyone else blocks the body in front of them.',
        tell: 'Under center, short yardage, a quick snap, the quarterback never leaves the center.',
        call: 'Third or fourth and inches. It is the highest-percentage play in football from there.',
        answer: 'Bodies in both A gaps, low. There is no cute counter. You win the gap or you do not.',
      },
      {
        id: 'zone-read',
        name: 'Zone read',
        look: 'The back runs one way. The quarterback might keep it the other way.',
        how: 'Inside or outside zone for the back. The backside end is left unblocked. If that end crashes the back, the quarterback keeps it. If the end sits for the quarterback, he hands it off.',
        tell: 'A run with one end unblocked, and the quarterback’s eyes on that end after the mesh.',
        call: 'When the backside end is wrecking your zone by crashing every time.',
        answer: 'The end plays the quarterback slowly, or you scrape: a linebacker takes the quarterback and the end takes the back. If you always crash, they will keep it. If you always sit, they will hand it off.',
      },
      {
        id: 'rpo',
        name: 'RPO',
        look: 'A run, with a slant, glance, or bubble thrown if a linebacker fits it.',
        how: 'Run-pass option. The line blocks a run. The quarterback reads one linebacker. If that backer steps up to the run, he throws behind him. If the backer stays in coverage, he hands it off. The throw is built in. It is not a scramble.',
        tell: 'A run block, a quick throw to a receiver who is behind a linebacker, and the back still getting the mesh.',
        call: 'When a linebacker is trigger-happy against the run. You make him wrong either way.',
        answer: 'He cannot cover the slant and fit the run. A end who plays the quarterback, or a trap coverage on the slant, is the fit. A pressure that hits before the read also ends it.',
      },
      {
        id: 'jet',
        name: 'Jet sweep',
        look: 'Fast motion across, and a handoff at the mesh.',
        how: 'A receiver is sprinting parallel to the line before the snap and takes the ball going full speed. The line often blocks zone the other way, so the defense flows wrong. The fake of a jet, with the ball handed to the back instead, is just as common.',
        tell: 'Full-speed motion, not a jog, arriving at the quarterback as the ball is snapped.',
        call: 'To get the ball to a fast player with a head start, or to freeze an edge.',
        answer: 'The edge has to be ready before the snap. Do not chase the motion with the whole front. If you do, the run the other way is the one they actually called.',
      },
    ],
  },
  {
    id: 'quick',
    title: 'Quick game',
    dek: 'The ball is out in about one second. These are the throws you see on early downs and against the blitz.',
    plays: [
      {
        id: 'slant',
        name: 'Slant',
        look: 'Inside release, then a 45-degree break across the corner’s face.',
        how: 'Three to six yards down. The receiver attacks the corner’s inside shoulder and cuts in. The throw leads him. A glance is the same break from a slot, often the tag on an RPO.',
        tell: 'A short inside break, not a route that crosses the whole field. The ball is out as he plants.',
        call: 'Against press, and against a linebacker who steps up. It is also the hot throw when a blitz comes.',
        answer: 'Jam and trail, or sit a hook player on the break. If they slant you, the offense’s next call is slant-and-go, or a flat behind the linebacker. That pair is slant-flat.',
      },
      {
        id: 'hitch',
        name: 'Hitch and curl',
        look: 'He stems up, stops, and turns back to the quarterback.',
        how: 'A hitch is five or six yards. A curl is a step deeper and sits down. Both are catch-and-turn routes. The throw is to the chest as he snaps around.',
        tell: 'A vertical stem and a sudden stop, no break inside or out.',
        call: 'Against an off corner who is giving a cushion. Easy yards until he drives on it.',
        answer: 'The off corner drives downhill on the throw. If he is jumping it, hitch-and-go is the shot: same stem, and he runs past the corner who bit.',
      },
      {
        id: 'out',
        name: 'Out',
        look: 'Five to eight yards, then a hard break to the sideline.',
        how: 'A 90-degree cut. It needs a clean release. The throw has to lead him toward the sideline before the corner can undercut it. A deep out is the same break at 12 to 15, and the quarterback throws it before the receiver has even finished the cut.',
        tell: 'A square break to the boundary, not a 45-degree corner route.',
        call: 'To move the chains and, on the deep out, to test a corner who is opening his hips early.',
        answer: 'Trail technique. Do not open the gate. Pair an out with a flat inside it and the flat defender has to choose. Throw whichever one he leaves.',
      },
      {
        id: 'flat',
        name: 'Flat',
        look: 'A back or a slot to the sideline immediately, shallower than an out.',
        how: 'He runs to the line and toward the numbers. Almost never a play by itself. It is the short piece of smash, flood, spot, and slant-flat. The throw is a wrist flick.',
        tell: 'A player leaving the backfield or the slot toward the sideline before anyone else has broken.',
        call: 'When a linebacker or a corner is sitting on the inside route and leaving the sideline.',
        answer: 'A flat defender who widens with him. If the flat is wide open, somebody left it to jump the slant or the hitch. Throw it until they stop.',
      },
      {
        id: 'stick',
        name: 'Stick',
        look: 'The inside receiver pushes to about six yards and either sits or speeds out.',
        how: 'Against zone he sits in the open space between linebackers. Against man he turns it into a speed out so the defender cannot catch up. The outside receiver is usually running a fade or a go as a clear-out.',
        tell: 'A short stop by the slot, with the outside receiver leaving the area.',
        call: 'A chain-mover against zone. The option break is why the same play looks different every week.',
        answer: 'The hook defender. If he jumps the sit, the corner route or the fade behind him is the next throw.',
      },
      {
        id: 'drag',
        name: 'Shallow cross',
        look: 'A receiver runs all the way across the field, two to four yards deep.',
        how: 'Also called a drag. He crosses under the linebackers. Man coverage has to chase him through traffic. Zone has to pass him from one defender to the next. A second crosser the other way is mesh.',
        tell: 'A body crossing the whole formation, low, not breaking at a landmark.',
        call: 'Against man, and against linebackers who are dropping deep.',
        answer: 'A robber, or a banjo: the two defenders switch the crossers instead of chasing them. If they sit on the drag, the post over the top is open. That pair is the drive concept.',
      },
      {
        id: 'hot',
        name: 'Hot route',
        look: 'The ball is out instantly because somebody came free.',
        how: 'A predetermined quick throw, usually a slant or a flat, sighted before the snap. If the blitz the quarterback counted on shows up, he throws hot and does not take the drop.',
        tell: 'A crowded line, no deep safety, and a throw that is out before the rush arrives. The receiver is not running a full route.',
        call: 'The answer to cover 0 and a zero blitz. You do not call it for style. You call it to survive.',
        answer: 'Do not show six rushers and an empty middle unless you can cover the hot. From the offense, if you see that look, this is the throw. A deep drop is a sack.',
      },
    ],
  },
  {
    id: 'concepts',
    title: 'Concepts',
    dek: 'These are packages of routes, not one receiver. The throw is whichever one the defense leaves.',
    plays: [
      {
        id: 'mesh',
        name: 'Mesh',
        look: 'Two receivers cross shallow and almost rub.',
        how: 'The cross is the play. It is a legal pick if both are running routes. Man defenders run into each other. One of the two is usually open right at the mesh.',
        tell: 'Two low crossers passing within a step of each other over the middle.',
        call: 'Against man, especially from a bunch.',
        answer: 'Switch the assignments, or play zone so there is nobody to rub. Chasing through the mesh is the mistake.',
      },
      {
        id: 'levels',
        name: 'Levels',
        look: 'Two in-cuts at different depths, usually five and ten yards.',
        how: 'A linebacker cannot sit on both. The throw is the depth he leaves. A third route alerts to the backside. Man gets picked because the routes cross. Zone has to pass the windows.',
        tell: 'Two receivers breaking inside, one under the other, same side or crossing the middle.',
        call: 'Against a zone linebacker who wants to jump the short in.',
        answer: 'Pass the routes off instead of one defender carrying both. If you jump the short one, the deeper in is the throw.',
      },
      {
        id: 'drive',
        name: 'Drive',
        look: 'A shallow cross, a dig, and a deep post or wheel.',
        how: 'Three answers for one defender. If the linebacker takes the cross, throw the dig. If the safety takes the dig, the post is behind him. The wheel is the version that attacks the flat defender who widened.',
        tell: 'A low crosser plus a square-in, with somebody else leaving deep.',
        call: 'When you want a built-in shot off a chain-mover.',
        answer: 'Carry the deep route and rally to the in. You will not cover all three. You cover the one their quarterback likes and live with the checkdown.',
      },
      {
        id: 'dagger',
        name: 'Dagger',
        look: 'One receiver posts. Another runs a dig into the space he cleared.',
        how: 'The post pulls the safety. The dig is thrown in front of that safety, usually 12 to 15 yards. Mills is the same idea from one side. It is a cover 2 and cover 4 beater.',
        tell: 'A vertical break toward the middle and a hard square-in underneath it.',
        call: 'When the safeties are deep and you want the window in front of them.',
        answer: 'Rob the dig with a lurking safety, or spin the coverage so the post is not single-covered. If the dig is always there, somebody is bailing with the post and leaving the in.',
      },
      {
        id: 'smash',
        name: 'Smash',
        look: 'A hitch or a short stop, with a corner route behind it.',
        how: 'A hi-lo on one side. The outside receiver hitches. The slot runs a corner to the sideline at about 45 degrees. In cover 2 the corner is supposed to jump the hitch and the safety takes the corner route. Throw whichever of them is late.',
        tell: 'A short stop outside and a receiver breaking toward the pylon behind him.',
        call: 'Against cover 2, and against any corner who is jumping short routes.',
        answer: 'The safety stays on top of the corner route and the corner drives the hitch only when that help is real. If the corner route is open every time, the safety is cheating the post. Next time throw the post.',
      },
      {
        id: 'spot',
        name: 'Spot',
        look: 'A triangle: corner route, a sit, and a flat.',
        how: 'Three levels to one side. The outside receiver runs the corner, the slot sits at about six, the back goes flat. The defender who jumps one leaves another. It is smash with a flat added.',
        tell: 'Three receivers on one side at three different depths, one of them sitting still.',
        call: 'Against zone in the red area, where the triangle is compressed and somebody is extra.',
        answer: 'Match the triangle. You do not need all three if the throw is late. You do have to know which one that quarterback likes.',
      },
      {
        id: 'flood',
        name: 'Flood',
        look: 'Three routes at three depths to one sideline.',
        how: 'Flat, an out or a corner, and a go. That side of the defense has two players for three routes. The throw is the open window. Spacing is the short version: hitch, sit, and flat, all underneath, spread across the width.',
        tell: 'A vertical, a medium break to the sideline, and a flat, all to one side.',
        call: 'From trips, when you have overloaded a side. Spacing is the call when you only need six yards.',
        answer: 'Carry the vertical and rally. If they flood you every time, the single receiver on the backside is open when you spin everyone over.',
      },
      {
        id: 'four-verts',
        name: 'Four verticals',
        look: 'Four receivers run go routes.',
        how: 'Cover 3 has three deep defenders. The fourth vertical, usually a seam between the hash and the linebackers, is the problem. The seams stretch the safeties and the mike.',
        tell: 'Everybody leaving straight down the field. No break.',
        call: 'Against cover 3 on long yardage. It is the simplest way to outnumber a three-deep shell.',
        answer: 'Cover 4, or a linebacker bailing with the seam. If they throw four verts every third and long, check to a draw. The linebackers have left.',
      },
      {
        id: 'yankee',
        name: 'Yankee',
        look: 'A post from one side and a deep cross from the other.',
        how: 'The over route crosses the field at 15 to 20. The post attacks the middle. A single high safety has to pick one. You throw the one he leaves. It is a cover 3 beater.',
        tell: 'Two deep routes crossing, from opposite sides, not a short mesh.',
        call: 'When you have one safety deep and you want him to choose.',
        answer: 'That safety stays deeper than both until the quarterback commits, and a robber takes away the cross. If he steps to the post early, the over is a touchdown.',
      },
      {
        id: 'seam',
        name: 'Seam',
        look: 'The slot runs straight up the hash.',
        how: 'He splits the linebacker and the safety. It is the inside vertical of four verts, and it is also a tag by itself. If the linebackers are sitting on crossers, the seam is the shot behind them.',
        tell: 'An inside receiver on a go, between the numbers and the hash, not a post.',
        call: 'Against linebackers who drop short and safeties who are outside.',
        answer: 'The mike carries him, or a safety caps him. If seams are open, your linebackers are sitting on the crossers. Carry the vertical.',
      },
      {
        id: 'dig',
        name: 'Dig',
        look: 'Twelve to fifteen yards, then a hard break inside.',
        how: 'A long stem and a square cut. The throw has to arrive as he crosses the linebacker’s face, before a robber can undercut it. It is the inside piece of dagger and drive.',
        tell: 'A deep square-in. Not a shallow cross, and not a post.',
        call: 'Against cover 2 and cover 3 when you want the window in front of the safeties.',
        answer: 'A hook linebacker or a robber under the break. Throw it early, or run a post behind the robber so he cannot sit there.',
      },
      {
        id: 'post',
        name: 'Post',
        look: 'He stems at the corner, then breaks to the middle.',
        how: 'The break is usually past twelve yards. Cover 1 and cover 3 put a safety in the deep middle to take it. Cover 2 leaves a hole between the two safeties, and the post into that hole is the shot, unless the mike is dropping into it.',
        tell: 'A break toward the goalpost, not a square-in and not a corner.',
        call: 'When the deep middle is empty, or when a safety has crept into the box.',
        answer: 'A single high safety who does not bite on play action. If he is in the box, this is the throw. If they play two deep with a mike dropping (Tampa 2), throw the corner instead.',
      },
      {
        id: 'corner-route',
        name: 'Corner',
        look: 'Ten to twelve yards, then a break toward the sideline pylon.',
        how: 'A 45-degree cut, not a square out. It attacks the cover 2 corner who is squatting on the hitch. Usually paired with that hitch. In the red zone it becomes a throw to the back of the end zone.',
        tell: 'A break to the corner of the end zone or the sideline, at an angle.',
        call: 'Against cover 2, and in the red zone when you want the pylon.',
        answer: 'The safety stays on top of it. If this route is open all day, your safety is cheating the post. Next time they should throw the post, and you should stop cheating.',
      },
      {
        id: 'comeback',
        name: 'Comeback',
        look: 'About fifteen yards, then he snaps back toward the quarterback.',
        how: 'Toward the sideline, so he can get out of bounds. The throw is to the outside shoulder as he stops. It looks a little underthrown on purpose.',
        tell: 'A deep stem and a sudden return back and outside. The clock stops if he steps out.',
        call: 'Two-minute drill, against a corner who is bailing deep.',
        answer: 'The corner who sits on it. The corner who bails too far gets beaten underneath. It is a hard throw, so you mostly see it from a quarterback who trusts his arm.',
      },
      {
        id: 'wheel',
        name: 'Wheel',
        look: 'He runs toward the flat, then bends up the sideline.',
        how: 'A back or a slot sells a flat and leaves the flat defender. The throw is deep, down the numbers. Post-wheel pairs it with a post so the safety has to pick.',
        tell: 'A flat stem that suddenly turns vertical along the sideline.',
        call: 'When a flat defender is jumping short throws and losing the wheel behind him.',
        answer: 'Carry the wheel. Do not jump the flat and give up the vertical. If you carry it, they check the ball down. That is a win.',
      },
      {
        id: 'option',
        name: 'Option route',
        look: 'The break changes with the defender.',
        how: 'The receiver sits, breaks in, or breaks out based on the linebacker’s leverage. You will not memorize one path. You memorize that the break was a reaction, not a missed route. Stick and spot use this all the time.',
        tell: 'The same player sits one snap and breaks out the next, against a different leverage.',
        call: 'Against zone linebackers, where a fixed route would run into a body.',
        answer: 'Play the man, not a spot. If you sit in a zone landmark, he will sit in the hole you are not standing in.',
      },
      {
        id: 'scissors',
        name: 'Scissors',
        look: 'A post and a corner crossing each other.',
        how: 'Two deep routes cross. The safety who runs with one leaves the other. It is the deep version of mesh.',
        tell: 'A post and a corner route passing in front of the same safety.',
        call: 'Against a single high safety who is aggressive.',
        answer: 'That safety stays home until the quarterback declares, and the corners carry the deep routes. Chasing one crosser is how the other one comes open.',
      },
      {
        id: 'fade',
        name: 'Fade and back-shoulder',
        look: 'A go to the sideline. Sometimes the throw is intentionally short.',
        how: 'A fade is a high ball to the boundary so only the receiver can get it. A back-shoulder is a go where the quarterback throws short of the receiver and he stops and comes back. Both show up in the red zone. The back-shoulder is how you throw a go against a corner who is playing over the top.',
        tell: 'A vertical along the sideline. On a back-shoulder, the receiver stops and turns back to a ball that looked underthrown.',
        call: 'Red zone, against press, and against a corner who will not play the short throw.',
        answer: 'Play through the receiver’s hands on the fade. On the back-shoulder, stay on top but do not turn and run so far that you cannot come back with him. If you never look back for the ball, the fade is a flag or a catch.',
      },
    ],
  },
  {
    id: 'play-action',
    title: 'Play action',
    dek: 'The run you have been using is the setup. The throw works because somebody believes the fake.',
    plays: [
      {
        id: 'pa-shot',
        name: 'Play-action shot',
        look: 'A run fake, then a post, a corner, or a deep cross.',
        how: 'The back attacks the line. The line sells the run for a beat, then passes rushers off. The quarterback pulls the ball and throws the route the fake cleared. It only works if you have actually been running the ball.',
        tell: 'A mesh that looks like a handoff, then the quarterback’s head comes up late.',
        call: 'When a team is fitting your run hard and a safety is creeping up.',
        answer: 'A safety who does not bite, and a linebacker who adds late instead of chasing the fake. If you fly up on every run fake, this is how they hit you.',
      },
      {
        id: 'boot',
        name: 'Bootleg',
        look: 'He fakes one way and rolls the other, with a flat in front of him.',
        how: 'The run fake pulls the defense. The quarterback rolls opposite, usually with a flat and a crossing route. The backside end is the read: if he chases the fake, the quarterback has a free edge. Naked boot is the same roll with nobody pulling to block that end. Waggle adds a deep cross behind the flat.',
        tell: 'The quarterback leaving the pocket opposite the back’s path. Pullers may be going with the fake, not with him.',
        call: 'When the end is crashing your zone or your power. You use that crash.',
        answer: 'The backside end stays home instead of chasing the back. A spy does the same job. If he chases, the boot is a first down every time, and they should keep calling it.',
      },
      {
        id: 'pa-cross',
        name: 'Play-action cross',
        look: 'A deep crosser after the fake.',
        how: 'The linebacker steps up for the run and the crosser runs behind him across the field. It is one of the hardest covers in football when the fake is good. Somebody has to pass the crosser off. Chasing him the whole way pulls a defender out of his zone.',
        tell: 'A run fake and then one receiver moving across the field at 10 to 18 yards, not at the line.',
        call: 'Off power, duo, or zone, once the linebackers are triggering.',
        answer: 'Pass him. Do not follow him from hash to hash. The flat or the checkdown is fine to give up. The crosser behind a biting linebacker is not.',
      },
    ],
  },
  {
    id: 'screens',
    title: 'Screens and tricks',
    dek: 'These punish a defense that is rushing up the field or flowing too fast to one side.',
    plays: [
      {
        id: 'bubble',
        name: 'Bubble screen',
        look: 'The slot catches it behind the line with blockers already in front.',
        how: 'A quick backward or lateral throw to the slot. Two receivers stalk-block. The offensive line often does not even move. It is a run thrown sideways.',
        tell: 'The ball is out to a slot who is moving sideways before the rush starts.',
        call: 'When the slot corner is blitzing, or the edge is dropping into coverage and leaving the perimeter.',
        answer: 'The edge crashes the bubble instead of dropping. If you crash every one, they will throw a now screen the other way, or a shot over the safety who flew up.',
      },
      {
        id: 'smoke',
        name: 'Now screen',
        look: 'The outside receiver takes one step and the ball is already there.',
        how: 'Also called a smoke screen. He is at the line. One teammate blocks the corner. There is less time to react than on a bubble.',
        tell: 'An instant throw to a receiver who has not run a route.',
        call: 'Against a soft corner, and as the fastest answer to an off-coverage cushion.',
        answer: 'The corner who is already on the line. If you play ten yards off, this is five free yards until you walk up.',
      },
      {
        id: 'tunnel',
        name: 'Tunnel screen',
        look: 'An inside receiver, with linemen releasing outside to block.',
        how: 'The ball goes to a slot or a tight end moving sideways, and offensive linemen are now lead blockers on the perimeter. Slower than a bubble, more hats in front.',
        tell: 'Offensive linemen running to the sideline after a short throw to an inside player.',
        call: 'When the defense is rushing inside and leaving the edge.',
        answer: 'A linebacker who reads the linemen releasing and beats them to the spot. If your linebackers drop deep, the tunnel is a run with blockers.',
      },
      {
        id: 'rb-screen',
        name: 'Backfield screen',
        look: 'The line lets the rush go, then releases, and the back catches it.',
        how: 'The tackles show pass, allow the defensive ends upfield, and then block them from the side or release to the linebackers. The back waits and catches it in the space the rush left. A middle screen is the same throw into the A gap.',
        tell: 'A pass set that turns into linemen leaving, and a back who has been standing still.',
        call: 'Against a four-man rush that is up the field, especially on long yardage.',
        answer: 'A tackle who sniffs it and does not rush past the ball, or a linebacker scraping under the release. If they screen you, the next same look is often a shot, because you started jumping it.',
      },
      {
        id: 'reverse',
        name: 'Reverse and end around',
        look: 'A fake one way. The ball goes to a receiver going the other way.',
        how: 'A jet or a handoff is the picture. A receiver taking the ball the opposite direction is the play. The backside pursuit has to stay honest or he is blocked by his own flow.',
        tell: 'The first action is a run or a sweep, and then a receiver has the ball going back across.',
        call: 'When the defense is fast to your base run.',
        answer: 'Slow the pursuit. One defender stays backside. If everyone flows, this is a house call, and they should keep it in the script until you stop flowing.',
      },
      {
        id: 'flea',
        name: 'Flea flicker',
        look: 'A run fake so complete they pitch it back and throw deep.',
        how: 'Handoff, the back takes two steps, then pitches back to the quarterback, who throws a shot. It is rare because it is slow. It works once, when the secondary has quit on the play.',
        tell: 'A back who does not really want to hit the hole, and a second exchange.',
        call: 'Once a game, after you have been running. Not on third and long, when nobody is biting.',
        answer: 'Do not abandon the deep middle on a run that looks too clean. One safety stays deep even when the box fills.',
      },
    ],
  },
  {
    id: 'coverage',
    title: 'Coverage',
    dek: 'Count the deep safeties first. One high, two high, or nobody. That tells you the family.',
    plays: [
      {
        id: 'cover-1',
        name: 'Cover 1',
        look: 'One deep safety. Everyone else is in man.',
        how: 'The safety is the help over the top. A robber may sit under the in-cuts. Because the corners have help deep, they can play tighter. The offense’s answers are rubs, meshes, and a double move if the safety bites.',
        tell: 'One safety deep, corners turned with their man, often a crowded line.',
        call: 'When you want to blitz and still have a deep middle. Call it as the defense.',
        answer: 'Slant, mesh, a pick from a bunch. If the single safety creeps up, the post is the shot. Call cover 1 only if that safety is a real deep player.',
      },
      {
        id: 'cover-0',
        name: 'Cover 0',
        look: 'No deep safety. The middle of the field is empty.',
        how: 'Man with no help, usually because everyone is rushing or the man corners are on an island. The quarterback has to throw hot. A deep drop is a sack.',
        tell: 'No safety over the top and more than five players at the line.',
        call: 'A zero blitz, when you believe the rush wins before the throw.',
        answer: 'Hot slant, flat, or the back leaking. From the defense, do not call this unless the hot is covered or the rusher is free. From the offense, this look means the ball comes out now.',
      },
      {
        id: 'cover-2',
        name: 'Cover 2',
        look: 'Two deep safeties. The corners squat on the hitch and the flat.',
        how: 'Each safety has a deep half. The corners play the short outside. The holes are the deep middle between the safeties, and the corner route behind a squatting corner. Smash and a post between the safeties are the throws.',
        tell: 'Both safeties deep, corners facing the quarterback and jumping short routes.',
        call: 'To take away slants, outs, and the quick game, and to keep two safeties from biting on play action.',
        answer: 'Smash, a corner route, or the hole-shot post. Tampa 2 drops the middle linebacker into that hole, so the post is no longer free and you throw the corner or run at the dropping backer.',
      },
      {
        id: 'cover-2-man',
        name: 'Cover 2 man',
        look: 'Two deep safeties, but the corners are in man, not squatting.',
        how: 'The short game shrinks because every receiver has a man and there is still deep help. Also called 2-man. Picks and posts into the hole are the stress.',
        tell: 'Two safeties high, but the corners are turned and running with receivers instead of jumping hitches.',
        call: 'When you want man underneath without giving up a deep shot over the top.',
        answer: 'A post between the safeties, or a rub that frees someone before the safety can help. Zone beaters like flood do less, because it is not zone.',
      },
      {
        id: 'cover-3',
        name: 'Cover 3',
        look: 'One deep middle, two corners deep, four underneath.',
        how: 'The strong safety can play the box, so it fits the run better than cover 2 or cover 4. The holes are the seams, a flood to the sideline, and a deep cross. Four verts puts four routes against three deep defenders.',
        tell: 'One safety in the middle, both corners bailing at the snap.',
        call: 'First down, when you want a safety in the run fit and a deep middle.',
        answer: 'Four verts, yankee, a seam, or a flood. If they play cover 3 every first down, motion and throw the seam behind the linebackers.',
      },
      {
        id: 'cover-4',
        name: 'Cover 4',
        look: 'Four defenders each take a deep quarter.',
        how: 'Also called quarters. It handles four verts and it handles play action, because the safeties are not crashing the run. It gives up the short middle, the glance, and the run if the safeties are too deep. Match quarters turns into man if the receivers release vertical. It looks like zone and then it follows you.',
        tell: 'Both safeties and both corners deep, with no single middle safety.',
        call: 'Against a four-verts team, and against play action.',
        answer: 'Inside zone, shallow cross, stick. If a "zone" corner suddenly runs with your slant, that was match, not a broken play. Throw the sit route instead of the vertical.',
      },
      {
        id: 'cover-6',
        name: 'Cover 6',
        look: 'One side is quarters. The other side is cover 2.',
        how: 'Quarter-quarter-half. The passing strength usually gets the quarters, so two defenders are deep to the trips. The weak side is a cover 2 half, with a corner who will jump a hitch.',
        tell: 'The two sides of the secondary do not look the same after the snap.',
        call: 'Against trips, when you want quarters to the overload and a squat corner on the single side.',
        answer: 'Attack the cover 2 side with a corner route, or the quarters side with a shallow cross. Do not call the same side every time or they will spin it.',
      },
      {
        id: 'robber',
        name: 'Robber',
        look: 'A safety or a linebacker sitting on the in-cut, under a one-high shell.',
        how: 'He is not deep and he is not rushing. He is lurking for the dig and the slant. The corners play with the safety still deep behind him. This kills the routes that break inside.',
        tell: 'One safety deep, and another defender poaching the middle instead of covering a man.',
        call: 'When a quarterback loves the dig.',
        answer: 'Throw the flat, or the go behind the robber. Stop throwing the dig until he leaves. If you keep throwing it, he will keep sitting there.',
      },
      {
        id: 'match',
        name: 'Pattern match',
        look: 'It starts as zone and then a defender runs with you.',
        how: 'Palms and 2-read carry a vertical and jump a short route. The rule depends on the release, not on a called man. That is why a slant sometimes gets jumped like man even though the shell looked like cover 4 or cover 2.',
        tell: 'A defender bails with a go and a teammate jumps the hitch. Nobody is "wrong." They passed you off by rule.',
        call: 'When you want zone against the run and man against the verticals.',
        answer: 'Sit down. The defender who carried the vertical cannot also sit on the hitch. Throw the route that stops.',
      },
    ],
  },
  {
    id: 'pressure',
    title: 'Fronts and pressure',
    dek: 'The front tells you where the run is supposed to go. The pressure tells you how fast the ball has to come out.',
    plays: [
      {
        id: 'nickel',
        name: 'Nickel and dime',
        look: 'Five defensive backs, or six.',
        how: 'Nickel takes a linebacker off for a slot corner. It is the defense you see against 11 personnel. Dime takes another linebacker off. Better against the pass, lighter against the run.',
        tell: 'Count the big linebackers. Two means nickel. One means dime.',
        call: 'Nickel on standard downs against 11. Dime on long yardage and empty.',
        answer: 'If they stay in dime, run the ball. If they stay in a big front against trips, throw the flood at the extra linebacker.',
      },
      {
        id: 'wide-9',
        name: 'Wide 9',
        look: 'The ends are lined up very wide.',
        how: 'They rush the passer and spill the run outside instead of squeezing it. Inside runs have more room. Edge runs get forced back... or bounce if the end is up the field.',
        tell: 'Ends outside the tackle, almost over the tight end, before the snap.',
        call: 'A pass-rush front. You trade some run fit for a faster edge.',
        answer: 'Inside zone right at the space they left, or a boot, because the end is up the field and the quarterback can get outside him.',
      },
      {
        id: 'tite',
        name: 'Tite front',
        look: 'The defensive tackles are shaded over the guards.',
        how: 'Built to take away inside zone. Both A gaps are crowded. The run is supposed to bounce outside, where the end and a linebacker are.',
        tell: 'Tackles heads-up on the guards, not in the gaps outside them.',
        call: 'Against an inside-zone team.',
        answer: 'Outside zone, toss, or a pass. Do not keep handing inside zone into a front that was built to stop it.',
      },
      {
        id: 'sim',
        name: 'Sim pressure',
        look: 'They show a blitz and then drop out.',
        how: 'A linebacker walks up and a defensive lineman drops, or the walked-up backer drops and somebody else comes. The guard blocks air. The dropper is sitting in a throwing lane.',
        tell: 'A crowded line before the snap, then one of them bailing as the ball is snapped. A rusher who was not there a second ago.',
        call: 'When you want the quarterback to throw hot into coverage.',
        answer: 'Throw the hot only if someone actually comes. If they dropped, take the deeper route that the dropper left. The fake blitz is the point.',
      },
      {
        id: 'green-dog',
        name: 'Green dog',
        look: 'A linebacker blitzes only because the back stayed in to block.',
        how: 'He is the man on the back. If the back releases, he covers him. If the back stays in, nobody needs to cover him, so he rushes. The extra rusher is free if the line did not count him.',
        tell: 'A linebacker who comes late, after he sees the back pass-protect.',
        call: 'Against teams that keep the back in on long yardage.',
        answer: 'Leak the back out. The green dog then has to cover him, and the rush is back to four.',
      },
      {
        id: 'stunt',
        name: 'Twist and stunt',
        look: 'Two rushers cross.',
        how: 'A tackle and an end switch gaps after the snap. The guard has to pass the rusher to the tackle. A free runner is often a late crosser, not a missed block.',
        tell: 'Rushers trading lanes. One loops behind the other.',
        call: 'When the offensive line is aggressive and leaving gaps early.',
        answer: 'Pass it off. Do not both chase the first rusher. From the offense, a quick throw ends the stunt before the looper arrives.',
      },
      {
        id: 'zero',
        name: 'Zero blitz',
        look: 'Cover 0 plus a rush. No safety, six or more coming.',
        how: 'The ball has to be out on a hot slant or a flat. If the protection picks it up, somebody is wide open because there is no deep help. If it does not, it is a sack or a strip.',
        tell: 'Empty middle of the field and a crowded line.',
        call: 'A shot you take when you think the rusher wins.',
        answer: 'Hot route. Do not drop back. From the defense, only bring it when the hot is occupied or the quarterback has been slow.',
      },
    ],
  },
  {
    id: 'situations',
    title: 'If they keep doing this',
    dek: 'The call that catches a team is the one their last three snaps made obvious.',
    plays: [
      {
        id: 'sit-zone',
        name: 'They are stopping inside zone',
        look: 'Linebackers fitting downhill, tackles slanting.',
        how: 'The run is what they want you to keep calling. The next call uses that fit.',
        tell: 'Your zone is going nowhere and the linebackers are fast.',
        call: 'Boot the other way, or an RPO glance behind the linebacker who is fitting.',
        answer: 'If you are the defense and they start booting, the backside end has to stop crashing. That is the adjustment to the adjustment.',
      },
      {
        id: 'sit-end',
        name: 'The end crashes every run',
        look: 'The backside end is in the backfield before the back is.',
        how: 'He is right until the quarterback stops handing it off.',
        tell: 'Same end, same crash, three runs in a row.',
        call: 'Zone read keep, or a naked boot. He is the player you are reading.',
        answer: 'He plays the quarterback for a series. The handoff will come back. Then you crash again.',
      },
      {
        id: 'sit-hitch',
        name: 'The corner jumps the hitch',
        look: 'He is driving on the short stop before the receiver has turned.',
        how: 'The hitch was open. Now he is playing it. The stem of the route has not changed.',
        tell: 'A corner who was off, now breaking downhill on every stop route.',
        call: 'Hitch-and-go. Same release, and he runs by the corner who bit.',
        answer: 'He drives, then recovers, or he only drives when he has safety help. If he never recovers, they should throw the go until he stops.',
      },
      {
        id: 'sit-cover3',
        name: 'Cover 3 all day',
        look: 'One safety middle, corners bailing, every first down.',
        how: 'They want a safety in the box. You get a deep middle and soft seams.',
        tell: 'The same shell on first and second down.',
        call: 'Four verts, a seam, or a flood to the sideline.',
        answer: 'Check to cover 4 on the long yardage, or carry the seam with a linebacker. Do not play three deep against four verticals and act surprised.',
      },
      {
        id: 'sit-cover2',
        name: 'Cover 2 all day',
        look: 'Two safeties, corners squatting.',
        how: 'The quick game is gone. The corner and the hole between the safeties are the plays.',
        tell: 'Corners jumping hitches, safeties staying home.',
        call: 'Smash, or a post between the safeties. If the mike starts dropping, that post is dead. Throw the corner.',
        answer: 'Tampa 2, or spin to cover 3 if they will not stop throwing the corner route.',
      },
      {
        id: 'sit-quarters',
        name: 'They play quarters',
        look: 'Four deep. The short middle is soft.',
        how: 'Verticals are covered. The run and the shallow cross are the food.',
        tell: 'Safeties and corners all bailing, linebackers left alone underneath.',
        call: 'Inside zone, stick, a shallow cross.',
        answer: 'Walk a safety down. If you stay four deep against the run, they will keep handing it off.',
      },
      {
        id: 'sit-box-safety',
        name: 'The safety is in the box',
        look: 'Eight defenders near the line. One safety left deep.',
        how: 'They are selling out for the run. The post is single-covered or uncovered.',
        tell: 'Count the box. Eight means the deep middle is a suggestion.',
        call: 'Play-action post. You have been running, which is why he walked up.',
        answer: 'He has to get back or you live with the post. There is no way to have eight in the box and two deep.',
      },
      {
        id: 'sit-robber',
        name: 'They rob the dig',
        look: 'A defender sitting in the middle, not rushing and not deep.',
        how: 'Your dig is his whole job. Throw it and he undercuts it.',
        tell: 'The same poacher on every in-breaker.',
        call: 'The flat, or the fade behind him. Stop feeding him the dig.',
        answer: 'If you leave the middle, he will go back to a normal zone. Then the dig is there again.',
      },
      {
        id: 'sit-screen',
        name: 'They fly up on screens',
        look: 'Linebackers and safeties sprinting downhill on every short throw.',
        how: 'The screen worked once. Now they are jumping it, which empties the deep field.',
        tell: 'Second-level players leaving their zones as soon as the linemen release.',
        call: 'The shot over the top on the next same look. Or go back to the screen the week after they sit on the shot.',
        answer: 'One screener stays home. The rest can rally. If everyone flies up, the fade is the call they should make, and you should expect it.',
      },
      {
        id: 'sit-long',
        name: 'Third and long, they drop seven',
        look: 'Only four rushers. Everybody else is deep.',
        how: 'The shot is covered. The short field is empty. This is the down for a draw or a screen, not for another vertical.',
        tell: 'A four-man rush and linebackers already at ten yards.',
        call: 'Draw or a backfield screen. Take what the drop gave you.',
        answer: 'Bring five, or keep a spy. Seven in coverage with no spy is an invitation.',
      },
      {
        id: 'sit-short',
        name: 'Third and short',
        look: 'They need one or two yards.',
        how: 'Sneak, inside zone, or stick. Cute is a loss unless the box is overloaded, in which case the slant behind the extra defender is the cute that works.',
        tell: 'A crowded line and a short chain.',
        call: 'The simple one, unless you have counted an extra hat in the box.',
        answer: 'Win the A gaps on the sneak. On the slant, you already chose to be light in the box. Live with it or walk a safety down and give up the post.',
      },
      {
        id: 'sit-red',
        name: 'Red zone',
        look: 'The field is short. Four verts do not fit.',
        how: 'Cover 2 gets stronger because the deep halves are tiny. The fade, the rub, the sneak, and the flat-slant matter more. A fade is the back-shoulder or the high ball to the pylon. A rub is two receivers crossing so man coverage collides.',
        tell: 'Inside the 20. The safeties have less room and the corners are tighter.',
        call: 'Fade against press. Mesh and bunch against man. Sneak on the goal line. Spot against zone.',
        answer: 'Man up and tackle. Deep zones have nowhere to drop. The throw that beats you here is usually the short one you left, or the fade you played underneath.',
      },
      {
        id: 'sit-two-minute',
        name: 'Two minute',
        look: 'They need the sideline, not the middle.',
        how: 'Outs and comebacks stop the clock if the receiver gets out of bounds. A crosser over the middle keeps it running. Throw the sideline unless you are fine with the clock, or you have a timeout.',
        tell: 'The hurry-up, and receivers finishing toward the boundary.',
        call: 'Comeback, out, and the occasional shot if they play soft to prevent the sideline.',
        answer: 'Knock him out of bounds only after the catch you can live with, or keep him in. A soft corner who gives the out is giving them the clock too.',
      },
    ],
  },
]
